# Generated by Django 4.0.3 on 2022-04-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('area', models.IntegerField(verbose_name='Площадь заказа')),
                ('budget', models.IntegerField(verbose_name='Бюджет')),
                ('deadline', models.DateField(verbose_name='Срок сдачи')),
                ('address_index', models.CharField(max_length=100, verbose_name='[Адрес] Индекс')),
                ('address_region', models.CharField(max_length=100, verbose_name='[Адрес] Область')),
                ('address_city', models.CharField(max_length=100, verbose_name='[Адрес] Город')),
                ('address_street', models.CharField(max_length=100, verbose_name='[Адрес] Улица')),
                ('address_office', models.CharField(max_length=100, verbose_name='[Адрес] Дом, корпус, помещение')),
                ('contact', models.CharField(max_length=300, verbose_name='Контактная информация')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Почта')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('price', models.IntegerField(verbose_name='Стоимость услуги')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
    ]
