# Generated by Django 4.0.4 on 2022-04-23 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('area', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площадь заказа')),
                ('budget', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Бюджет')),
                ('deadline', models.DateField(verbose_name='Срок сдачи')),
                ('address_index', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='[Адрес] Индекс')),
                ('address_region', models.CharField(max_length=100, verbose_name='[Адрес] Область')),
                ('address_city', models.CharField(max_length=100, verbose_name='[Адрес] Город')),
                ('address_street', models.CharField(max_length=100, verbose_name='[Адрес] Улица')),
                ('address_office', models.CharField(max_length=100, verbose_name='[Адрес] Дом, корпус, помещение')),
                ('contact', models.CharField(max_length=300, verbose_name='Контактная информация')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость услуг')),
                ('contact', models.CharField(max_length=300, verbose_name='Контактная информация')),
                ('worktime_start', models.TimeField(verbose_name='[Время работы] Начало')),
                ('worktime_end', models.TimeField(verbose_name='[Время работы] Окончание')),
                ('additionalinfo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Дополнительная информация')),
                ('weekends', models.CharField(choices=[('без выходных', 'без выходных'), ('с выходными, требуется уточнение', 'с выходными, требуется уточнение')], max_length=50)),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
    ]
