# Generated by Django 4.0.4 on 2022-05-22 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_executor_average_rank_executorrank_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Стоимость услуг'),
        ),
    ]
