# Generated by Django 4.0.4 on 2022-05-22 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_executor_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='address_index',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='[Адрес] Индекс'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='area',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Площадь заказа'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='budget',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='minarea',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Минимальная площадь для заказа'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Стоимость услуг'),
        ),
    ]
